"""empty message

Revision ID: 407503be4912
Revises: 4a1f1adf773b
Create Date: 2026-02-20 21:43:54.557074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407503be4912'
down_revision = '4a1f1adf773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
