"""added voting

Revision ID: 6005e2eaef0b
Revises: f944bd9975de
Create Date: 2026-02-21 11:01:15.012078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6005e2eaef0b'
down_revision = 'f944bd9975de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_column('review_end_time')

    # ### end Alembic commands ###
