"""added arena

Revision ID: 6718a13fb8f6
Revises: 70e2cdd8b96b
Create Date: 2026-02-21 10:04:24.791459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6718a13fb8f6'
down_revision = '70e2cdd8b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('opponent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creator_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opponent_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('creator_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('opponent_code', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['opponent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('opponent_code')
        batch_op.drop_column('creator_code')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('opponent_ready')
        batch_op.drop_column('creator_ready')
        batch_op.drop_column('opponent_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
