"""added unsubscribe

Revision ID: 73b594f75a10
Revises: 6005e2eaef0b
Create Date: 2026-02-23 15:40:47.204977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b594f75a10'
down_revision = '6005e2eaef0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_to_daily_prompt', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscribed_to_daily_prompt')

    # ### end Alembic commands ###
