"""empty message

Revision ID: 759ffaa0af83
Revises: da67345927ce
Create Date: 2026-01-31 14:31:25.151766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ffaa0af83'
down_revision = 'da67345927ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
