"""add_submit_flags

Revision ID: a1bc468ccc4d
Revises: 6718a13fb8f6
Create Date: 2026-02-21 10:22:45.046757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bc468ccc4d'
down_revision = '6718a13fb8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opponent_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_column('opponent_submitted')
        batch_op.drop_column('creator_submitted')

    # ### end Alembic commands ###
