"""add points

Revision ID: d07e5cc5295a
Revises: 70e2cdd8b96b
Create Date: 2026-02-28 21:00:24.894182

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d07e5cc5295a"
down_revision = "70e2cdd8b96b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("points", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("points")

    # ### end Alembic commands ###
