"""empty message

Revision ID: e47e4edb37a6
Revises: 70e2cdd8b96b
Create Date: 2026-02-28 17:01:22.182279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47e4edb37a6'
down_revision = '70e2cdd8b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_to_daily_prompt', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')
        batch_op.drop_column('subscribed_to_daily_prompt')

    # ### end Alembic commands ###
