"""Add streak_days and last_active_date to User

Revision ID: f8dd2d9ae1e4
Revises: 852cad9bb17c
Create Date: 2026-02-28 22:11:07.690514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dd2d9ae1e4'
down_revision = '852cad9bb17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_active_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_date')
        batch_op.drop_column('streak_days')

    # ### end Alembic commands ###
